### ISSUE TITLE
get attribution error of foo

### ISSUE THREAD

**Issue by Tikitaka02** [stanfordnmbl/opencap-processing#43] opened 2022-12-13 20:00 UTC
Hello, I keep getting the attribution error like the one below.

AttributeError: module 'foo' has no attribute 'foo'

It is coming from the generateF function in utilsOpenSimAD.py

def generateF(dim):
    import foo
    importlib.reload(foo)
    cg = ca.CodeGenerator('foo_jac')
    arg = ca.SX.sym('arg', dim)
    y,_,_ = foo.foo(arg)
    F = ca.Function('F',[arg],[y])
    cg.add(F)
    cg.add(F.jacobian())
    cg.generate()

How can I solve this problem?

I appreciate your answer in advance.

**Comment by antoinefalisse** [comment] 2022-12-13 21:02
@Tikitaka02 thanks for reporting. What platform are you using? Are you running example_kinetics.py?
Did you follow all the [install instructions](https://github.com/stanfordnmbl/opencap-processing#general)?

**Comment by Tikitaka02** [comment] 2022-12-13 21:35
Thank you for your reply. I am using windows and running on example_kinetics.py. I followed the instruction, and the code worked previously for other kinetic simulations. I think the foo.py which contains the foo function will be created under the \UtilsDynamicSimulations\OpenSimAD\opensimAD-install\windows\bin, but I cannot use the function.

**Comment by antoinefalisse** [comment] 2022-12-13 22:06
Did you change anything? It is surprising if it worked before but not anymore. Are you running some of the examples or is it with your own data?

**Comment by Tikitaka02** [comment] 2022-12-13 22:26
I cloned the repo and followed the setup again, but it gives the same error. Previously I analyzed for walking, but this time, I tried cutting-edge movement. Therefore, I changed the motion_type = 'other'. That is the only change I created like below.

session_type = 'overground' # Options are 'overground' and 'treadmill'.
session_id = ".......confidential......"
case = '0' # Change this to compare across settings.
# Options are 'squat', 'STS', and 'jump'.
if session_type == 'overground': 
    trial_name = 'movement' 
    if trial_name == 'squat': # Squat
        motion_type = 'squats'
        repetition = 1
    elif trial_name == 'STS': # Sit-to-stand        
        motion_type = 'sit_to_stand'
        repetition = 1
    elif trial_name == 'jump': # Jump  
        motion_type = 'jumping'
        time_window = [1.3, 2.2]
    else:
        motion_type = 'other'

**Comment by antoinefalisse** [comment] 2022-12-13 22:34
Would you be willing to share your session_id? I can then try to reproduce the error - it will be hard to debug otherwise. You can share it privately with me: afalisse@stanford.edu.

**Comment by Tikitaka02** [comment] 2022-12-13 22:38
sure no problem

01ec7299-bba5-494b-9f67-fcccb517d657

**Comment by antoinefalisse** [comment] 2022-12-14 06:41
How are you running the script? From the terminal or within an IDE? I just tried, only changing this in the code:
```
session_type = 'overground' # Options are 'overground' and 'treadmill'.
session_id = "01ec7299-bba5-494b-9f67-fcccb517d657"
case = '0' # Change this to compare across settings.
# Options are 'squat', 'STS', and 'jump'.
if session_type == 'overground': 
    trial_name = 'movement' 
    if trial_name == 'squat': # Squat
        motion_type = 'squats'
        repetition = 1
    elif trial_name == 'STS': # Sit-to-stand        
        motion_type = 'sit_to_stand'
        repetition = 1
    elif trial_name == 'jump': # Jump  
        motion_type = 'jumping'
        time_window = [1.3, 2.2]
    elif trial_name == 'movement': # Jump  
        motion_type = 'other'
        time_window = [0.5, 2.5]
```

and I don't get any error. Do you get an error if you try walking again?

**Comment by antoinefalisse** [comment] 2022-12-14 17:21
Thanks for letting me know. Good luck for the simulations, looking at your motion you might want to have periodic constraints since the subject is starting and ending the motion is almost the same pose. See [here ](https://github.com/stanfordnmbl/opencap-processing/blob/main/UtilsDynamicSimulations/OpenSimAD/settingsOpenSimAD.py#L491)an example of how to set periodic constraints for certain coordinates.

Closing this issue

**Closed by antoinefalisse** 2022-12-14 17:21 UTC
